#!/bin/sh
# See LICENSE file for copyright and license details.

set -e

usage() {
	echo 'usage: apps-menu file' >&2
	exit 1
}

[ "$1" ] || usage

cat "$1" | sort | sed '/^$/d' | bemenu -p 'Apps' | xargs swaymsg exec

exit 0
