#!/bin/sh
# See LICENSE file for copyright and license details.

set -e

usage() {
	echo 'usage: apps-menu file' >&2
	exit 1
}

if [ -z "$1" ]; then 
	usage
fi

sort "$1" | sed '/^$/d' | bemenu -p 'Apps' | xargs swaymsg exec
