#!/bin/sh
# See LICENSE file for copyright and license details.

set -e

die() {
	echo "Error: $1" >&2
	exit 1
}

sync() {
	mbsync -a -c "$IMAP_CONFIG" || die 'Failed to sync'
}

sync
neomutt
sync

exit 0
