#!/bin/sh
# See LICENSE file for copyright and license details.

set -e

usage() {
	echo 'usage: aristatus' >&2
	exit 1
}

if cras_done=$(cras -D 2>/dev/null) && cras_tot=$(cras -A 2>/dev/null); then
	cras_str="$cras_done/$cras_tot"
fi

wifi_str=$(iwctl station wlan0 show | grep 'Connected network' | \
           sed -E 's/^.*Connected network[[:space:]]*//; s/[[:space:]]*?$//')

batt_str=$(acpi | awk '{ print $3, $4 }' | tr -d ',[:lower:]')

aud_str=$(amixer sget Master | tail -n 1 | \
          sed -E 's/.*\[(.*%)\].*\[(on|off)\].*/\1 \2/')

date_str=$(date +'%Y-%m-%d %H:%M %p')

echo "| ${cras_str:---} | wifi: ${wifi_str:---} | batt: $batt_str " \
     "| audio: $aud_str | $date_str"
