#!/bin/sh
# See LICENSE file for copyright and license details.

set -e

if tasklst=$(NO_COLOR=1 cras 2>/dev/null | grep '#'); then
	task=$(printf '[Exit]\n%s' "$tasklst" | bemenu -p 'Tasks' -l 10 -i)
else
	exit 1
fi

if ! [ "$task" ] || [ "$task" = '[Exit]' ]; then
	exit 0
fi

tasknum=$(echo "$task" | cut -d ' ' -f 1 | sed -E 's/#([0-9]*?)/\1/')
stat=$(echo "$task" | cut -d ' ' -f 2)

if [ "$stat" = "[TODO]" ]; then
	flag='-t'
else
	flag='-T'
fi

cras "$flag" "$tasknum" > /dev/null
