#!/bin/sh
# See LICENSE file for copyright and license details.

if tasklst=$(NO_COLOR=1 cras 2>/dev/null | grep '#'); then
	task=$(echo "$tasklst" | bemenu -p 'Tasks' -l 5 -i)
else
	exit 1
fi

! [ "$task" ] && exit 1

tasknum=$(echo "$task" | cut -d ' ' -f 1 | sed -E 's/#([0-9]*?)/\1/')
stat=$(echo "$task" | cut -d ' ' -f 2)

if [ "$stat" = "[TODO]" ]; then
	cras -t "$tasknum"
else
	cras -T "$tasknum"
fi

exit 0
