#!/bin/sh
# See LICENSE file for copyright and license details.

set -e

EMOJI_VER="15.0"
EMOJI_DB="${EMOJI_DB:-$HOME/.emoji-db.txt}"

usage() {
	echo 'usage: emoji-menu [-f]' >&2
	exit 1
}

getemojidb() {
	echo 'Downloading emoji database...' >&2
	curl "https://unicode.org/Public/emoji/$EMOJI_VER/emoji-test.txt" \
	| awk '!/^#/ && /fully-qualified/ && match($0, /# .*?$/) {
		   print substr($0, RSTART + 2, RLENGTH - 2)
               }' \
	> "$EMOJI_DB"
}

while getopts :f opt; do
	case "$opt" in
	f) force=1 ;;
	?) usage ;;
	esac
done

shift $((OPTIND - 1))
if [ "$1" ]; then
	usage
fi

if [ "$force" ] || ! [ -f "$EMOJI_DB" ]; then
	getemojidb
fi

bemenu -p 'Emoji:' -l 30 < "$EMOJI_DB" | cut -d ' ' -f 1 | tr -d '\n' | wl-copy
