#!/bin/sh

usage() {
	>&2 echo 'usage: sfeedbar [-u]'
	exit 1
}

case "$1" in
	-u) sfeed_update ;;
	-*) usage ;;
esac

url=$(sfeed_plain "$HOME/.sfeed/feeds/"* | bemenu -p 'Feeds' -l 35 -i | \
      sed -n 's@^.* \([a-zA-Z]*://\)\(.*\)$@\1\2@p')
[ "$url" ] && xdg-open "$url"
