#!/bin/sh

set -e

usage() {
	echo 'usage: sfeedbar [-u]' >&2
	exit 1
}

while getopts :u opt; do
	case "$opt" in
	u)	sfeed_update "$HOME/.config/sfeed/sfeedrc" ;;
	?)	usage ;;
	esac
done

url=$(sfeed_plain "$HOME/.cache/sfeed/feeds/"* | sort -r -k 1 | \
      bemenu -p 'Feeds' -l 20 -i | \
      sed -n 's@^.* \([a-zA-Z]*://\)\(.*\)$@\1\2@p')
[ "$url" ] && xdg-open "$url"

exit 0
